### ISSUE TITLE
Add "Anti-Censorship" to the core of libp2p

### ISSUE THREAD

**Issue by TheRook** [libp2p/specs#514] opened 2023-02-07 23:09 UTC
I don't see how "spying" is related to the human rights violation of censorship.   Seeing as; cjdns, Tor and i2p are all blocked in China, I think that proves my point that censorship is not the same as privacy.   I think that libp2p is in a unique space to tackle the problem of IP address filters to prevent access to content.

**Comment by marten-seemann** [comment] 2023-02-08 00:08
Duplicate of #513.

**Closed by marten-seemann** 2023-02-08 00:08 UTC
